---
title: "Filosofía Primaria de Ananda Marga Cap.1 - Anandamurti  "
layout: post
comments: true
tags: Anandamurti
published: true
---


 

### Ch. 1 ¿Qué Es el Dharma?

Los seres humanos son los seres más evolucionados. Poseen conciencia claramente reflejada, y esto los hace superiores a los animales. Ningún otro ser tiene un claro reflejo de la conciencia tales. Los seres humanos pueden distinguir entre el bien y el mal con la ayuda de su conciencia, y cuando en problemas que puedan encontrar una salida, con su ayuda. A nadie le gusta vivir en la miseria y el sufrimiento, los seres humanos mucho menos, cuya conciencia se pueden encontrar los medios de alivio. La vida sin dolor y sufrimiento es una vida de felicidad y dicha, y que es lo que la gente desea. Todo el mundo está en la búsqueda de la felicidad; de hecho, es la naturaleza de las personas para buscar la felicidad. Ahora vamos a ver lo que uno hace para lograrlo y si se consigue por esos medios.

En su búsqueda de la felicidad son las personas primero atraídos hacia los goces físicos. Ellos acumulan riqueza y tratar de alcanzar el poder y la posición para satisfacer sus deseos de felicidad. Aquel que tiene cien rupias no se cumple con él, uno se esfuerza por mil rupias, pero incluso los que poseen miles de rupias no satisface. Uno quiere un millón, y así sucesivamente. Entonces se ve que una persona que tenga influencia en un distrito quiere extenderla sobre una provincia, los líderes provinciales quieren convertirse en líderes nacionales, y cuando han logrado que no se arrastra en un deseo de liderazgo mundial. La mera adquisición de riqueza, poder y posición no satisface a una persona. La adquisición de algo limitado sólo crea la necesidad de más, y la búsqueda de la felicidad no encuentra fin. El hambre de poseer es interminable. Es ilimitado e infinito.

Sin embargo digna o noble logro, no logra poner en la búsqueda ilimitada de las personas de descanso para la felicidad. Los que anhelan después de la riqueza no estarán satisfechos hasta que puedan obtener riqueza ilimitada. Tampoco el buscador de poder, posición y prestigio satisfechos hasta que él o ella puede obtener estos en proporciones ilimitadas, ya que todos estos son objetos del mundo. El mundo mismo es finito y no puede proporcionar objetos infinitos. Naturalmente, por lo tanto, la mayor adquisición mundo, incluso si es todo el globo, sería no asegura nada de un carácter infinito y permanente. ¿Cuál es, entonces, que la infinita cosa eterna que proporcionará la felicidad eterna?

El Cosmic sola entidad es infinito y eterno. Es la única que no tiene límites. Y el anhelo eterno de los seres humanos para la felicidad sólo puede ser saciada por la realización del Infinito. El carácter efímero de las posesiones mundanas, poder y posición sólo puede conducir a la conclusión de que ninguna de las cosas del mundo finito y limitado puede establecer en reposo la necesidad eterna de la felicidad. Su adquisición más que da lugar a una mayor anhelo. Sólo realización del Infinito puede hacerlo. El Infinito puede ser sólo uno, y que es la Entidad Cósmica. Por lo tanto, sólo es la Entidad cósmica que puede proporcionar la felicidad eterna - la búsqueda de la que es la característica de todo ser humano. En realidad, detrás de este impulso humano se esconde el deseo, el anhelo, para el logro de la Entidad Cósmica. Es la propia naturaleza de cada ser vivo. Esto por sí solo es el dharma de cada persona.

La palabra dharma significa "propiedad". La palabra en espanol es la "naturaleza", "característica" o "propiedad". La naturaleza del fuego es quemar o producir calor. Es la característica o propiedad de fuego y también se llama la naturaleza del fuego. Del mismo modo, el dharma o de la naturaleza de un ser humano es buscar la Entidad Cósmica.

El grado de la divinidad en los seres humanos es indicado por su conciencia claramente reflejada. Todo ser humano, después de haber evolucionado a partir de animales, tiene, por lo tanto, dos aspectos - el aspecto animal, y el aspecto consciente que distingue a una persona de los animales. Animales muestran predominantemente la animalidad, mientras que los seres humanos debido a una conciencia bien reflejada también poseen racionalidad. La animalidad de seres humanos les da una inclinación hacia la vida animal o goce físico. Ellos, bajo su influencia, ven a comer, beber y gratificación de otros deseos físicos. Ellos se sienten atraídos hacia estos y corren detrás de ellos bajo la influencia de su animalidad, pero éstos no proporcionan la felicidad como su anhelo de que es infinita. Animales están satisfechos con estos goces limitados como su impulso no es infinito. Sin embargo gran cantidad de cosas que se ofrecen a un animal puede ser, que tomará sólo los que necesita y no se molestará por el resto. Pero los seres humanos sin duda actuar de manera diferente en estas condiciones. Esto sólo establece que los animales están satisfechos con el limitado para que el deseo del ser humano no tiene límites, aunque el deseo de disfrute tanto se pide y se rige por el aspecto de los animales de la vida. La diferencia entre los dos es debido a la posesión por el ser humano de una conciencia claramente reflejada, cosa que carecen de los animales. La naturaleza infinita de la necesidad humana de la felicidad absoluta es debido a su conciencia en paz. Es esta conciencia por sí sola, que no está satisfecho con el placer físico de la posesión, poder y posición - lo que a pesar de sus enormes proporciones, sólo son de carácter transitorio. Es la conciencia que crea en el ser humano el anhelo de la Entidad Cósmica.

Los objetos del mundo - los goces físicos - no saciar la sed del corazón humano para la felicidad. Sin embargo, nos encontramos con que las personas se sienten atraídos por ellos. La animalidad en personas les atrae hacia la gratificación de los deseos animales, pero la racionalidad de su conciencia permanece insatisfecho ya que todos ellos son transitorios y de corta duración. Ellos no son suficientes para poner en reposo el hambre infinita e ilimitada de la conciencia humana. Hay, por lo tanto, un duelo constante en los seres humanos entre la animalidad y la racionalidad. El aspecto de los animales les empuja hacia placeres terrenales instantánea, mientras que su conciencia, al no estar satisfecho con estos, los atrae hacia la Entidad Cósmica - Infinito. Esto se traduce en la lucha entre el aspecto de los animales y la conciencia. ¿Habían los placeres carnales derivados de poder y posición sido infinita e interminable, se habrían fijado en reposo la eterna búsqueda de la conciencia de la felicidad. Pero no lo hacen, y es por eso la gloria efímera de alegrías temporales nunca se puede asegurar una paz duradera en la mente humana y llevar a la gente al éxtasis.

Sólo la conciencia bien reflejada que diferencia al ser humano de los animales. ¿Es entonces no imprescindible para los seres humanos para hacer uso de su conciencia? Si su conciencia está latente detrás de su animalidad, las personas están obligados a comportarse como animales. Ellos, de hecho, llegan a ser peores que animales como, aunque dotado de conciencia bien reflejada, no hacen uso de ella. Estas personas no merecen la condición de seres humanos. Son animales con forma humana.

La naturaleza de la conciencia es la búsqueda de lo infinito o darse cuenta de la Entidad Cósmica. Sólo aquellos que hacen uso de su conciencia y siga sus dictados merecen ser llamados seres humanos. Por lo tanto, cada persona, haciendo pleno uso de su conciencia se refleja, se gana el derecho a ser llamado un ser humano y encuentra su dharma o la naturaleza ser sólo la búsqueda de la Entidad Infinita o cósmico. Este anhelo de lo infinito es la calidad innata o dharma que caracteriza la condición humana de las personas.

La felicidad se deriva por conseguir lo que uno desea. Si uno no consigue lo que uno desea, no se puede ser feliz. Uno se vuelve triste y miserable. La conciencia claramente reflejado en la gente, que es lo único que los distingue de los animales, busca la Entidad Cósmica o el Infinito. Y así la gente obtiene la felicidad real sólo cuando pueden alcanzar la Entidad Cósmica o entrar en el proceso de alcanzarlo. La conciencia no quiere alegrías terrenales porque el ser finito ninguno de ellos satisfacerla. La conclusión a la que llegamos a es que el dharma de la humanidad es darse cuenta de lo Infinito o la Entidad Cósmica. Es sólo por medio de este dharma que la gente puede disfrutar de la felicidad eterna y la felicidad.

La característica o dharma de los seres humanos es alcanzar Brahma. Está, por lo tanto, hay que ver si Brahma existe o no, ya que sería inútil tratar de conseguir algo que en realidad no existe. Si Brahma existe, debemos saber lo que es.

Cada acción que una persona realiza, parece haber sido ejecutado por sus órganos físicos, los indriyas. Estos órganos o indriyas son diez. Y parece que casi cada acción que aparece una persona realiza a se han realizado a causa de estos diez indriyas. Sin embargo, esto no es en realidad tan. Si la mente no funciona detrás de ellos, los indriyas por sí mismos no pueden realizar ninguna acción. Es la mente la que trabaja y los diez indriyas son más que los instrumentos mediante los cuales se ejecuta el trabajo. La acción que se origina en la mente sólo encuentra su manifestación externa con la ayuda de los indriyas. Para explicar esto, podemos tomar el ejemplo de una persona que mira un libro. Es sólo la mente que visualiza el libro con la ayuda de los ojos. Si la mente no funciona los ojos no serán capaces de ver el libro. Por ejemplo, una persona en un estado de inconsciencia debido a la anestesia o alguna otra razón no será capaz de ver el libro, incluso si sus ojos están bien abiertos. En tal estado inconsciente de los ojos no estén dañados, sin embargo, no pueden realizar su función natural debido a que el contacto con la mente está suspendido. Es por ello que bajo los efectos de la anestesia, los órganos o indriyas no funcionan, aunque se mantienen en perfecto orden. A menudo, cuando estamos absortos en sus pensamientos, no nos damos cuenta de una persona o reconocer a un amigo de pie justo en frente de nosotros. Esto es sólo porque, a pesar de que nuestros ojos estén en perfecto orden y bien abiertos, la mente, que en realidad lleva a cabo todas las acciones, no hace uso de los indriyas, los ojos. Es la mente la que trabaja y los indriyas sólo ayudan en su manifestación externa.

Si es sólo la mente que funciona, vamos a ver cómo actúa a través de estos indriyas. Por ejemplo, mirando un libro es una acción que la mente realiza con la ayuda de los ojos. Cuando la mente ve un libro, lo que realmente sucede es que la mente, con la ayuda de los ojos, toma la forma de algo que llamamos un libro. Esta forma que la mente toma es diferente de la imagen que se forma en la retina, como la mente puede ver y llegar a ser como un libro, incluso cuando los ojos están cerrados; pero los ojos no pueden ver cuando la mente no funciona. Así es la mente la que toma la forma de un libro durante la percepción visual. Esta parte de la mente que toma la forma del libro se denomina Citta o materia mental. Pero incluso si la Citta toma la forma de un libro, tiene que haber algo más que el Citta que hace el trabajo de ver. La parte de la mente que hace el trabajo de ver se llama Ahamtattva o "yo hago". Pero "yo" no voy a ser capaz de ver nada menos que "yo" existe. Así que debe haber otra parte de la mente que es diferente de estos dos. Esta tercera parte de la mente es la parte que da la sensación de "yo" y se llama Mahattattva. Sin el sentimiento de la existencia del "yo" o el conocimiento de sí mismo, se puede realizar ninguna acción. Este sentimiento de "yo" o el conocimiento del yo viene de Mahattattva o Buddhitattva. El nombre colectivo para estos tres - Citta, Ahamtattva y Mahattattva - es la mente o Antahkarana: la fuerza psíquica introspectiva. Pero estas tres partes de la mente son sólo las manifestaciones externas de la mente. Es con este espíritu que se realiza la acción de ver un libro, y esto se denomina asimilación psíquica de Tanmātra Rupa.

Tanmātra es un nuevo término y debe ser explicado. La fracción microscópica de una onda radiada desde un objeto y recibida por los indriyas se llama Tanmātra o inferencia. Para explicar esto más, se puede decir que la idea de un libro se agarra con la ayuda de Tanmātra Rupa (la vibración ideatory de los nervios crea una imagen o figura en la mente), cuando uno mira el libro. Pero si los ojos están cerrados o si uno está en un lugar oscuro, todavía se pueden reconocer el libro a través del tacto. Aquí la idea del libro es asimilado debido a otro Tanmātra, es decir, la Tanmātra del tacto o la percepción táctil. Una vez más, si alguien cae un libro fuera de la vista o fuera de su alcance, es posible identificarlo como un libro a través de la Tanmātra auditivo. Citta entra en contacto con los Tanmatras sólo cuando Ahamtattva quiere que lo haga. El acto de ver o identificar el libro debe ser realizada por Ahamtattva como Citta por sí mismo no posee la capacidad para llevar a cabo cualquier función. Cuando Ahamtattva o la parte de la mente que trabaja quiere ver un libro, Citta entra en contacto con los órganos de la vista, es decir, los ojos. Los ojos reciben el Tanmātra Rupa del libro. Este Tanmātra que siempre está presente en el ambiente en forma de ondas, que atacan contra Citta través de los ojos, que forman una especie de puerta para llevar Citta en contacto con el mundo exterior. Citta entonces toma la forma del libro, y Ahamtattva identifica o lo ve como por la forma que ha tomado Citta. Del mismo modo, cuando Ahamtattva quiere escuchar algo que pone Citta en contacto con los órganos de la audición, los oídos. Las orejas reciben el Tanmātra sonido, que está siempre presente en el entorno físico, a través del medio de las ondas sonoras. Citta, sobre el impacto de esta Tanmātra, se convierte en el sonido en sí mismo, y Ahamtattva oye ese sonido. Esto demuestra que Citta toma la forma de lo que sea Ahamtattva deseos o hace. Para decirlo de otra manera, Citta manifiesta las acciones que lleva a cabo Ahamtattva.

Ya se ha explicado que Citta, Ahamtattva y Mahattattva o Buddhitattva constituyen la mente. Citta sólo tiene la capacidad de tomar la forma que quiere Ahamtattva. Del mismo modo Ahamtattva sólo tiene la capacidad de realizar acciones. Sólo puede trabajar. Tiene que haber algo para hacer que funcione. Ese algo es Mahattattva o Buddhitattva, que le da a uno la sensación de "yo". Este sentimiento de "yo" se deriva de la mente y este "yo" en la mente hace Ahamtattva y Citta realizar sus respectivas funciones. Sin este "yo" no es posible sentir o ver un libro, aunque, bajo la influencia de Ahamtattva, Citta toma la forma del libro. Pero entonces este "yo" es sólo una parte de la mente. Es decir, no es otro "yo" que es la posesión de "yo", o el "yo", que sabe que hay una mente. La existencia del "yo" en la mente sólo demuestra que hay otra entidad real que está más allá de la mente y que conoce la existencia de la mente. Este "yo", que es la entidad testigadora y testigo de la existencia de la mente y la existencia de Buddhitattva o la sensación de "yo", se llama Atman o conciencia unidad. Así través de la introspección y se concentra el pensamiento se observa que Atman y la mente, es decir, la conciencia de la unidad y de la mente, son dos entidades separadas.

Atman, o la conciencia unidad y la mente son dos entidades separadas, sin embargo, deben estar relacionados entre sí. En primera instancia, parece que soy consciente de mi existencia. Luego el mismo "yo" que parece demostrar mi existencia me hace trabajar, y una parte de mi mente llamada Citta toma la forma del libro a través de Tanmatras para permitirme ver el libro. El "yo" que me da la conciencia o el "yo", que es testigo de la existencia de mi mente y en la misma del "yo", que da la sensación de "yo existo" es la conciencia Atman o unidad. El "yo" que da la sensación de "yo existo", y también demuestra la existencia de Atman o la conciencia unitaria, es Mahattattva. El "yo" que funciona o ve el libro es Ahamtattva y la parte de la mente que toma la forma del libro y permite Ahamtattva para ver que es Citta. Esto demuestra que el mismo "yo" tiene una función diferente en cada etapa. ¿Cómo estas diferentes funciones en el mismo "yo" se producen necesita más aclaraciones. La declaración "yo existo" presupone la presencia de "yo", que es el testimonio de esta existencia. Esta entidad testigadora es la conciencia Atman o unidad y su presencia se establece por el sentimiento de la existencia que uno muestra por de uno cada acción. Que esta afirmación del "yo existo" es diferente de Atman o unidad de conciencia se ve en el hecho de que este "yo" presupone la presencia de mi Atman o conciencia unidad. Este sentimiento demuestra que la conciencia unidad es sólo la conciencia y que sin la existencia de conciencia no es posible. Sin conciencia no puede haber una sensación de la existencia. Entonces, ¿qué va a ser testigo de la existencia del "yo"? La conciencia es por lo tanto esencial para crear la sensación de Mahattattva o Buddhitattva. Para ser explícito, Mahattattva o Buddhitattva no puede existir sin Atman o conciencia unidad.

Pero la entidad testigadora y el puro sentimiento del "yo" parecen ser diferentes formas funcionales de la misma "yo". De hecho, el "yo" que testiga de mi existencia, también se manifiesta como el "yo" del "yo existo". El testigo de "yo" es la conciencia de unidad o Atman y se manifiesta como Mahattattva o Buddhitattva y así establece su propia existencia. Es la entidad o unidad presenciar conciencia que al tomar posesión de la función del "yo" de "yo existo", se llama Mahattattva o Buddhitattva. Por lo tanto la conciencia unidad no es sólo la conciencia, sino que también tiene una calidad con la ayuda de los cuales se manifiesta a través de diferentes funciones. Esta calidad no es la conciencia, ya que de lo contrario no sería necesario que la conciencia unidad a manifestarse como Mahattattva y expresarse a sí misma como el "yo" del "yo existo", que es diferente de la entidad testigadora. Conciencia y su calidad son, por tanto, dos entidades separadas en la conciencia Atman o unidad. Como esta calidad es diferente de la conciencia, que debe haber sido obtenido de alguna parte. Tiene que haber algún otro factor para calificar Atman para que sea manifiesta como Mahattattva. Lo que da esta calidad de Atman se llama Prakrti. En otras palabras, que se debe a Prakrti calificar Atman que se manifiesta como Mahattattva y tiene la sensación de "yo".

Prakrti necesita una explicación. Prakrti es la entidad que controla los fenómenos naturales. Prakrti es ni la naturaleza ni la calidad. Por ejemplo, la calidad de la combustión se dice que es la naturaleza del fuego. Tiene que haber algo que le da esta calidad al fuego; así como hay alguna entidad que da calidad a la conciencia unidad. Lo que califica conciencia unidad es Prakrti y no la calidad que se exhibe, debido a su influencia. Prakrti es una palabra sánscrita y se deriva pra - KR + ktin y significa hacer algo de una manera especial. Conciencia Unidad establece su existencia sólo al ser calificada por Prakrti. En otras palabras, Prakrti califica conciencia unidad o Atman para darle la sensación de su existencia. La energía es necesaria para llevar a cabo cualquier acción. Como Prakrti realiza la acción de Atman calificación o la conciencia unitaria, Ella es una fuerza única. Ella es el principio que califica conciencia unidad. Es Prakrti que, por su influencia en la conciencia de unidad, le da las cualidades de diferentes funciones. Prakrti es una fuerza única - un principio. Pero algunas de las preguntas que surgen son: cuyo principio es ella, y ¿De dónde vienen?

Prakrti es el principio de Purus'a, y es por su propio principio de que Purus'a está influenciada y calificado. Como Prakrti es el principio de Purus'a, Ella debe existir dentro Purus'a. De hecho, ella siempre lo hace. Conciencia unidad y su Prakrti nunca pueden ser separados unos de otros, así como el principio de la quema de fuego que no se puede separar del fuego. Cualquier cosa que adquiere una cualidad característica debido a la influencia de un principio o fuerza, no puede existir si ese principio o fuerza se retira de ella. Los dos siempre van de la mano, y también lo hacen unidad de la conciencia y su principio, Prakrti. La conciencia de la unidad y su Prakrti son inseparables, como las dos caras de una hoja de papel. La única función de Prakrti es crear continuamente diferentes formas por su influencia sobre la conciencia.

Conciencia Unidad es la entidad testigadora y se da cuenta de su existencia sólo cuando es calificado para manifestarse como "yo" del "yo existo." El principio de Prakrti que establece la existencia de la conciencia unidad calificar Purus'a se llama Sattvaguṇa, el principio sensible, y la parte de la mente que así se formó para dar la sensación de "yo existo" se llama Mahattattva o Buddhitattva. Será más correcto decir que bajo la influencia de Sattvaguṇa, conciencia unidad se manifiesta como Mahattattva o Buddhitattva.

Cada acción presupone la existencia. A menos que yo existo, no voy a ser capaz de ver. Aquí también nos encontramos con que "yo" tiene dos funciones o aspectos diferentes. La primera es la entidad o de la conciencia de testimonio, que, con el fin de probar o darse cuenta de su existencia, ha adquirido la sensación de "yo existo", y el mismo "yo" ahora realiza la función de ver. El "yo" del "yo existo" es el Buddhitattva que, mientras que ver algo, asume la función de ver, además de establecer la existencia de la conciencia unidad. Cuando la conciencia unidad está influenciada por Prakrti, se manifiesta como Buddhitattva. Del mismo modo, la capacidad adicional para realizar una acción también es causada por la influencia de Prakrti en Buddhitattva. Prakrti también estará presente en Buddhitattva ya que es sólo una manifestación de la conciencia individual, y Prakrti está destinada a ser con la unidad de la conciencia donde sea y en cualquier forma que pueda existir. El principio o Guna de Prakrti que da a esta calidad o capacidad de Buddhitattva se llama rajoguna, el principio mutativo. Así, cuando Buddhitattva está influenciada por Prakrti, muestra dos funciones o aspectos. Este último, que se pone de rajoguna y que le da la capacidad o calidad para llevar a cabo una acción, se conoce como Ahamtattva. Es decir, Buddhitattva manifiesta como Ahamtattva cuando influenciado por rajoguna o el principio mutativo de Prakrti.

Cada acción está obligado a tener un resultado en el final. Por ejemplo, cuando nos fijamos en un libro el resultado es ver el libro. ¿Cómo vemos un libro se explicó anteriormente. Citta, que es una parte de la mente, recoge la forma de producción de Tanmātra del libro y en sí se convierte en la forma del libro. Es ese libro que Ahamtattva ve. Citta toma la forma de lo que Ahamtattva quiere que sea. Cuando Ahamtattva ve un libro, Citta se convierte en ese libro, y cuando se oye un sonido, Citta se convierte en ese sonido. Por lo tanto, Citta es totalmente dependiente de Ahamtattva por su forma. Citta sigue cambiando su forma a la licitación de Ahamtattva. Debe ser entonces muy estrechamente relacionada con Ahamtattva. ¿Cómo se forma Citta necesita aclaración. Citta, como se explicó anteriormente, es una parte de la mente, y Buddhitattva y Ahamtattva son las otras dos partes. Buddhitattva y Ahamtattva son manifestaciones de la conciencia unidad formada debido a la influencia de Sattvaguṇa de Prakrti sobre ella y de rajoguna sobre Buddhitattva. En otras palabras, es la unidad de conciencia que, bajo la influencia de Prakrti, ocupa la función de Ahamtattva en la segunda etapa. De ahí Prakrti está presente en Ahamtattva y está obligado a calificar aún más. De hecho, es debido a la calificación Prakrti Ahamtattva que se manifiesta como Citta. La calidad de Prakrti que influye Ahamtattva se llama Tamoguṇa, el principio estático. Es como consecuencia de la influencia de Tamoguṇa que Ahamtattva, o el "yo" que lleva a cabo acciones, tiene que tomar la imagen mental del resultado de su acción. Esto significa que cuando "yo" veo un libro, es "yo" que se convierte en el libro. Otro "yo" por lo tanto entra en estar bajo la influencia de Tamoguṇa. Es este "yo", que toma la forma de la imagen mental del libro durante la percepción. Este "yo", que se convierte en el libro o toma la forma del libro es Citta. Por lo tanto, es la conciencia la unidad que se manifiesta gradualmente a sí mismo como Citta.

En los párrafos anteriores se estableció por la lógica y el razonamiento de que es sólo la conciencia unitaria que, bajo la influencia de los diferentes principios de su Prakrti, manifiesta gradualmente a sí mismo como Citta, y como resultado de esto, la mente llega a ser. La existencia de la conciencia unidad es esencial para la mente, que es sólo una manifestación gradual de la conciencia unidad bajo la influencia de calificación de Prakrti. Mind, de hecho, no se puede formar sin la presencia de la conciencia Atman o unidad. Pero sabemos que la mente está presente en cada individuo. De ahí que la conciencia Atman o unidad también está presente en cada individuo. Hay innumerables individuos en este universo, y como Atman o conciencia unidad se refleja en cada uno de ellos, no parecen ser muchos Atmans o conciencias unidad. El nombre colectivo para todos estos Atmans o unidad conciencias es Paramatman, Bhúmácaetanya, Brahma o Bhagavan. Así como doce unidades hacen una docena, veinte crea una partitura, y el nombre colectivo para un número muy grande de soldados es un ejército, el nombre colectivo para todas las conciencias unidad es Paramatman, Bhúmácaetanya o Bhagavan. El nombre de Bhagavan no debe interpretarse como una figura humana poderosa con las manos y los pies de gran alcance. Es la colección de todos nuestros Atmans. La palabra más cercana en espanol que se puede utilizar para Atman o conciencia unidad es "alma", por lo que Bhagavan también puede ser llamado Conciencia Universal o Alma Universal. Esto demuestra que existe Bhagavan y que Existe como Paramatman o Alma Universal, Bhúmácaetanya o Conciencia Cósmica, o Brahma, la bienaventuranza eterna.
1955

Poco a poco traducimos estas publicaciones en espanol.  Pueden descargar todas las publicaciones de Anandamurti en ingles:<a href="https://cmdr0.blaucloud.de/index.php/s/juHPQAnDa2yaWor">https://cmdr0.blaucloud.de/index.php/s/juHPQAnDa2yaWor<a/>
